# The *Salmonella* Concord mystery: a genomic investigation of a potential outbreak in Ethiopia


Today, you will take on the role of a microbial genomics investigator and analyse bacterial isolates obtained from patients in Ethiopia. The samples originate from stool specimens collected from young patients presenting with severe gastrointestinal symptoms.

Because of concerns about possible invasive bacterial infection in these young patients, several were treated empirically with antibiotics. For all patients, first-line treatment with was not effective, and therapy was switched to either ceftriaxone or ciprofloxacin. However, in one case, ciprofloxacin also failed, and the patient was subsequently treated with azithromycin, which successfully resolved the infection.

Given the possibility of a localized outbreak affecting multiple patients, you were asked to investigate whether these cases are epidemiologically linked. After culturing the bacteria in the laboratory, all isolates were identified as *Salmonella*. Phenotypic antimicrobial susceptibility testing showed resistance to selected antibiotics *in vitro*.


# Objectives

Whole-genome sequencing was subsequently performed at AHRI using both Illumina and Oxford Nanopore Technologies platforms. Your task in this exercise is to analyse these genomic data, starting from the raw sequencing reads. You will assess data quality, confirm species identity, infer serotype, explore antimicrobial resistance determinants, and investigate genetic relatedness among isolates. Ultimately, you will evaluate whether these cases represent a single outbreak strain, and consider whether the lineage is likely endemic to Ethiopia or potentially imported.

## Software


```{bash}

conda create -n concord_dataset -c conda-forge -c bioconda sra-tools
conda install -n concord_dataset -c conda-forge -c bioconda filtlong

conda install bioconda::flye



```


## Retrieving Nanopore data

We have nanopore data available on the SRA/ENA, that was generated using the (nowadays old) R9.4.1 data. Despite being of lower quality than the R10.4.1 data we have nowadays, the sequencing depth and coverage were high, so the overall quality is accurate and sufficient for *de novo* assembly and downstream analyses. 


::: {.callout-note collapse="true"}
## Optional background to retrieve the unassembled reads yourself from the European Nucleotide archive and perform *de novo* genome assembly.

Note that is is not required for the course, and we have given you the assembled fasta files. The main reason for that is that assembly programs take quite some time to run. Ideally, you run the step yourself, but if you don't have the time or resources to do so, you can just use the fasta files we have provided.

For retrieving the data, we'll use a tool named 'fasterq-dump' from NCBI. It can be parallelised, en hence it should be relatively fast.


```{bash}
conda activate concord_dataset


runs=(
  ERR9855645
  ERR9855644
  ERR9855648
  ERR9855650
  ERR9855647
  ERR9855646
  ERR9855652
  ERR9855653
  ERR9855651
  ERR9855649
)

CPUS=8

mkdir -p concord_fastq
for run in "${runs[@]}"
do
  fasterq-dump "$run" --threads "$CPUS" --progress --outdir fastq
done

```

Oh no, fasterq-dump downloaded unzipped fastq files! We want to gzip them to save some space on our computer or server, but we have 8 CPUs, so we can do it in parallel. For that, we can use a tool named 'pigz', which is a parallel implementation of gzip.

```{bash}

pigz -p "$CPUS" fastq/*.fastq

```

Now we can use a tool named 'filtlong' to filter the reads based on quality and length, and to select the best 100× of the genome size (5 Mb for *Salmonella*). This will help us to reduce the computational time for assembly, while still retaining the most informative reads.

```{bash}

# 100× of 5 Mb = 500 Mb
TARGET_BASES=500000000

for file in *.fastq.gz
do
  filtlong --target_bases $TARGET_BASES "$file" | gzip > "${file%.fastq.gz}.best500Mb.fastq.gz"
done
```

With these subsets, we can now run the assembly program 'flye' to perform *de novo* assembly of the genomes. If you use the subsets, the process will be a bit faster. 

We will specify the genome size, the number of threads to use, and the number of iterations for polishing the assembly.

```{bash}
# run flye 

genome=5m
threads=16

for fq in *.best500Mb.fastq.gz; do
 
  # assemble
  flye --nano-hq "$fq" \
    --genome-size "$genome" \
    --out-dir flye_${fq%.best500Mb.fastq.gz} \
    --threads $threads \
    --iterations 2
done



```

For the *Salmonella Concord* paper  
(<https://www.nature.com/articles/s41467-023-38902-x>), from which these data were sourced, the program **Trycycler** was used for genome assembly.  

In that study, we used not only **Flye** but also several other assemblers, and we semi-manually curated the assemblies to obtain the best possible results.  

Today, an exciting new tool called **Autocycler**  
(<https://github.com/rrwick/Autocycler/wiki>) automates this entire process. It is well worth exploring and may save you considerable time.


:::

You can skip the section above where the reads are downloaded. Instead, we will move directly to the more interesting part: identifying features in our freshly generated *de novo* genome assemblies.

The FASTA files can be found here:

<!-- add path or link -->

If you are unsure about the difference between *de novo* assembly and read mapping, see the information box below.

::: {.callout-note}
## De novo assembly vs mapping

* **De novo assembly** constructs a genome from scratch by overlapping and merging sequencing reads without relying on an existing reference. It is useful when no reliable reference genome is available or when you are exploring new organisms. De novo assembly can reveal novel sequences and structural variants, but it requires more compute power and careful curation.

* **Mapping** (also called reference‑based assembly) aligns each read to a known reference genome. This approach is faster and less computationally demanding than de novo assembly, and it is often used to identify variants relative to the reference. However, mapping cannot discover sequences that are absent from the reference and may miss complex structural changes.

:::

## retrieving short read data for the same samples of the long read data


Back in the day (2021), we often performed Nanopore sequencing in combination with Illumina sequencing, to have both long and short reads for the same samples. This is useful for hybrid assembly, polishing, and other downstream analyses. 

While nowadays we could just perform Nanopore sequencing only, it is still useful to have the short read data for benchmarking and comparison purposes. Lets get the corresponding Illumina sequences: 


```{bash}
SRR8552256
ERR9516343
ERR9516195
ERR9516199
ERR9516333
ERR9516357
ERR9516339
SRR10604677
ERR9516323
ERR9516355
```