project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Pathogen genomics workshop"
  subtitle: "Advanced bioinformatics course - FA5 2026"

  author:
    - name: Bethlehem Adnew
      orcid: 0000-0002-6108-9534
      email: bethlehem.adnew@ahri.gov.et
      affiliations:
        - name: Armauer Hansen Research Institute
          url: https://ahri.gov.et/
    - name: Eline Turcksin
      email: eline.turcksin@uantwerpen.be
      affiliations:
        - name: University of Antwerp
          url: https://www.uantwerpen.be/en
    - name: Katlijn De Meulenaere
      orcid: 0000-0003-0723-9009
      email: kdemeulenaere@itg.be
      affiliations:
        - name: Institute of Tropical Medicine Antwerp
          url: https://www.itg.be
    - name: Oren Tzfadia
      orcid: 0000-0002-7096-8063
      email: otzfadia@itg.be
      affiliations:
        - name: Institute of Tropical Medicine Antwerp
          url: https://www.itg.be
    - name: Pieter Monsieurs
      orcid: 0000-0003-2214-6652
      email: pmonsieurs@itg.be
      affiliations:
        - name: Institute of Tropical Medicine Antwerp
          url: https://www.itg.be
    - name: Pieter Moris
      orcid: 0000-0003-4242-4939
      url: https://pmoris.github.io
      email: pmoris@itg.be
      affiliations:
        - name: Institute of Tropical Medicine Antwerp
          url: https://www.itg.be
    - name: Selien Oostvogels
      orcid: 0000-0002-6524-0246
      email: soostvogels@itg.be
      affiliations:
        - name: Institute of Tropical Medicine Antwerp
          url: https://www.itg.be
    - name: Wim Cuypers
      orcid: 0000-0002-1895-3526
      email: wim.cuypers@uantwerpen.be
      affiliations:
        - name: University of Antwerp
          url: https://www.uantwerpen.be/en

  date: "2026-02-25"
  date-format: iso

  license: "CC BY 4.0"

  chapters:
    - index.qmd
    - content/refresher.qmd
    - part: "From reads to variants"
      chapters:
        - content/genomics/setup.qmd
        - content/genomics/pipeline-overview.qmd
        - content/genomics/tools-and-formats.qmd
        - content/genomics/qc.qmd
        - content/genomics/mapping.qmd
        - content/genomics/variant-calling.qmd
        # - content/bacterial_genomics/bacterial_genomics.qmd
    - content/phylogenomics/phylogenetics_exercise.qmd
    - content/chimera/snp_mapping_chimera_alphafold.qmd

    #   - part: "Bioinformatics file formats and tools"
    #   # chapters:
    #     # - content/bioinf/bioinf-file-formats.qmd
    # - part: "Malaria Molecular Surveillance"
    #   chapters:
    #       - content/mms/mms_usecases
    #       - content/mms/molecular_markers
    #       - content/mms/practical_variants_of_interest
    #       - content/mms/genetic_diversity
    # - part: "Population genetics"
    #   chapters:
    #       - content/popgen/population_genetics
    #       - content/popgen/micro_evolution
    #       - content/popgen/practical_LD
    #       - content/popgen/visualisation
    #       - content/popgen/practical_PCA
    #       - content/popgen/relatedness
    #       - content/popgen/multilocus
    #       - content/popgen/ibd
    #       - content/popgen/population_structure
    #       - content/popgen/practical_ibd
    # - part: "Case studies"
    # - content/population-genetics.qmd
    # - content/phylogenetics.qmd
    # - part: "Computational literacy" # aka things that ~can~ will go wrong aka what I wish I had known
    - content/references.qmd
    # https://quarto.org/docs/books/book-structure.html#parts-appendices
    # parts can either be a stand-alone file with intro
    # or just a name for only grouping files below

  # appendices:
  #   - content/unix/appendix-unix.qmd

  # references: https://quarto.org/docs/books/book-structure.html#references

  back-to-top-navigation: true
  page-navigation: true

  page-footer:
    left: |
      &copy; 2026 [AHRI](https://ahri.gov.et/) - [ITM](https://www.itg.be/en/) - [UA](https://www.uantwerpen.be/en/) [![](https://mirrors.creativecommons.org/presskit/icons/cc.svg){fig-alt="CC" height=1.2em}](https://creativecommons.org/licenses/by/4.0/) [![](https://mirrors.creativecommons.org/presskit/icons/by.svg){fig-alt="BY" height=1.2em}](https://creativecommons.org/licenses/by/4.0/)
    center: "Source available on [GitHub](https://github.com/AHRI-ITM-UA/FA5-advanced-bioinformatics-course-2026)"

    right: Built with [Quarto](https://quarto.org/).
    # background: "#f8f9fa"

  reader-mode: true

  search:
    location: sidebar
    type: textbox # overlay
    show-item-context: true
    # https://quarto.org/docs/reference/projects/books.html#search

  sidebar:
    # https://quarto.org/docs/websites/website-navigation.html#side-navigation
    # style: "docked"
    style: "floating"
    search: true
    # background: dark
    # logo:
    # logo-alt:
    # logo-href:


  # favicon:
  # twitter-card: true
  site-url: https://AHRI-ITM-UA.github.io/FA5-advanced-bioinformatics-course-2026
  repo-url: https://github.com/AHRI-ITM-UA/FA5-advanced-bioinformatics-course-2026/
  repo-actions: [source, issue]

# comments:
#   hypothesis: true

toc: true
toc-depth: 4
toc-expand: true
# toc-location: left
number-sections: true
# number-depth: 2

# citation-location: margin
reference-location: margin
bibliography: content/references.bib

appendix-style: default

format:
  html:
    theme:
      light: [flatly, ./styles/custom.scss]
      dark: [darkly, ./styles/custom.scss]
      # https://quarto.org/docs/websites/website-tools.html#dark-mode
      # If a navbar has been specified, the toggle will appear in the top right corner of the nav bar.
      # If there is no navbar present, but a sidebar has been specified, the toggle will appear in the same location that the sidebar tools appears (adjacent to the title or logo in the sidebar).
      # If there is no navbar or sidebar present, the toggle will appear in the top right corner of the page.
    highlight-style: arrow # monokai nord dracula arrow
    mainfont: "Atkinson Hyperlegible Next"
    monofont: "Fira Code"
    linestretch: 1.5
    code-fold: true
    html-math-method: katex
    lightbox: true

strip-comments: true

editor: source

# https://quarto.org/docs/publishing/github-pages.html#freezing-computations
execute:
  freeze: auto

language:
  title-block-author-plural: "Teaching team and organising committee"
